name: Create a Tag

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag Name'
        required: true

jobs:
  create-tag:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ github.event.inputs.tagName }}",
              sha: context.sha
            })
